### ISSUE TITLE
Add this repo to javascript-obfuscator organization

### ISSUE THREAD

**Issue by sanex3339** [tomasz-oponowicz/grunt-javascript-obfuscator#11]
Hi. Can you transfer this repo to `javascript-obfuscator` organization?
https://github.com/javascript-obfuscator

**Comment by tomasz-oponowicz** [comment]
@sanex3339 

Hello Timofey, nice to meet you :)

In principle it’s a good idea. 

I've contacted with you directly in order to cover details.

Best,
Tomasz
